# Ejercicios clase 1

Importando librerias

In [30]:
import numpy as np
from unittest import TestCase
import math

Una matriz de prueba

In [31]:
matriz = np.array([[1,0,3],[-1,-5,7],[8,-10,2]], dtype=np.float64)
print(matriz)

[[  1.   0.   3.]
 [ -1.  -5.   7.]
 [  8. -10.   2.]]


## Ejecicio #1: Operaciones Matriciales
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático: 
Computar las normas l0, l1, l2, l-infinito. _Todas las operaciones debe ser vectorizadas._

Ref: [medium]https://montjoile.medium.com/l0-norm-l1-norm-l2-norm-l-infinity-norm-7a7d18a4f40c

In [40]:
def vector_norm_l0(m):
    a = m != 0
    return np.sum(a, axis=1) # Cuenta los elementos distintos de cero (axis = 1, suma por filas)

def vector_norm_l1(m):
    a = np.abs(m)
    return np.sum(a, axis=1)

def vector_norm_l2(m):
    a = np.abs(m)**2
    return np.sqrt(np.sum(a, axis=1)) 

def vector_norm_inf(m):
    a = np.abs(m)
    return np.max(a, axis=1)

In [45]:
norm0 = vector_norm_l0(matriz)
print('Norma l0: {}'.format(norm0))

norm1 = vector_norm_l1(matriz)
print('Norma l1: {}'.format(norm1))

norm2 = vector_norm_l2(matriz)
print('Norma l2: {}'.format(norm2))

normInf = vector_norm_inf(matriz)
print('Norma lInf: {}'.format(normInf))

Norma l0: [2 3 3]
Norma l1: [ 4. 13. 20.]
Norma l2: [ 3.16227766  8.66025404 12.9614814 ]
Norma lInf: [ 3.  7. 10.]


Definiendo test:

In [42]:
class NormTestCase(TestCase):

    def test_norm_l0(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        expected = np.array([4, 4])
        result = vector_norm_l0(a)
        np.testing.assert_equal(expected, result)

        a = np.array([[1, 0, 0, 4], [5, 6, 0, 8]])
        expected = np.array([2, 3])
        result = vector_norm_l0(a)
        np.testing.assert_equal(expected, result)

    def test_norm_l1(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        expected = np.array([10, 26])
        result = vector_norm_l1(a)
        np.testing.assert_equal(expected, result)

        a = np.array([[-1, -2, -3, -4], [-5, -6, -7, -8]])
        expected = np.array([10, 26])
        result = vector_norm_l1(a)
        np.testing.assert_equal(expected, result)

    def test_norm_l2(self):
        a = np.array([[1, 2], [3, 4]])
        expected = np.array([math.sqrt(5), math.sqrt(25)])
        result = vector_norm_l2(a)
        np.testing.assert_allclose(expected, result)

    def test_norm_inf(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        expected = np.array([4, 8])
        result = vector_norm_inf(a)
        np.testing.assert_equal(expected, result)

Corriendo test

In [43]:
test_obj = NormTestCase()

test_obj.test_norm_l0()
test_obj.test_norm_l1()
test_obj.test_norm_l2()
test_obj.test_norm_inf()

## Ejecicio #2: Sorting 
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se requiere computar la norma l2 de cada vector. Una vez obtenida la norma, se debe ordenar las mísmas de mayor a menor. Finalmente, obtener la matriz original ordenada por fila según la norma l2. _Todas las operaciones debe ser vectorizadas._

In [71]:
def sorting_vectors_by_norm_l2 (m):
    norm2 = vector_norm_l2(m)
    ind = np.argsort(norm2)
    return m[ind[::-1]]

In [72]:
sort_l2 = sorting_vectors_by_norm_l2(matriz)

print('Matriz: {}'.format(matriz))
print('Sort l2: {}'.format(sort_l2))

Matriz: [[  1.   0.   3.]
 [ -1.  -5.   7.]
 [  8. -10.   2.]]
Sort l2: [[  8. -10.   2.]
 [ -1.  -5.   7.]
 [  1.   0.   3.]]


Definiendo test:

In [73]:
class SortTestCase(TestCase):

    def test_sorting_by_norm_l2(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        sorted_a = sorting_vectors_by_norm_l2(a)
        np.testing.assert_equal(np.array([[5, 6, 7, 8], [1, 2, 3, 4]]), sorted_a)

        a = np.array([[1, 2, 3, 4], [10, 11, 12, 13], [5, 6, 7, 8]])
        sorted_a = sorting_vectors_by_norm_l2(a)
        np.testing.assert_equal(np.array([[10, 11, 12, 13], [5, 6, 7, 8], [1, 2, 3, 4]]), sorted_a)

Corriendo test:

In [74]:
test_obj = SortTestCase()

test_obj.test_sorting_by_norm_l2()

## Ejecicio #3: Indexing
El objetivo es construir un índice para identificadores de usuarios, es decir _id2idx_ e _idx2id_.
Para ello crear una clase, donde el índice se genere en el constructor. Armar métodos _get_users_id_ y _get_users_idx_.

* Identificadores de usuarios : users_id = [15, 12, 14, 10, 1, 2, 1]
* Índice de usuarios : users_id = [0, 1, 2, 3, 4, 5, 4]

```
id2idx =  [-1     4     5    -1    -1    -1     -1    -1    -1    -1     3     -1      1    -1     2     0]
          [ 0     1     2     3     4     5      6     7     8     9    10     11     12    13    14    15]

id2idx[15] -> 0 ; id2idx[12] -> 1 ; id2idx[3] -> -1
idx2id[0] -> 15 ; idx2id[4] -> 1
```

In [ ]:
class Indexer(object):
    